a = eval(input("digite a parte real de c1\n"))
b = eval(input("digite a parte imaginaria de c1\n"))
c = eval(input("digite a parte real de c2\n"))
d = eval(input("digite a parte imaginaria de c2\n"))
c1 = complex(a,b)
c2 = complex(c,d)
print(f"{c1} + {c2} = {c1+c2} = {c2} + {c1}")
print(f"{c1} * {c2} = {c1*c2} = {c2}*{c1}")
e = eval(input("digite a parte real de c3\n"))
f = eval(input("digite a parte imaginaria de c3\n"))
c3 = complex(e,f)
print(f"({c1}+{c2})+{c3} = {c1+c2+c3} = {c1}+({c2}+{c3})")
print(f"({c1}*{c2})*{c3} = {c1*c2*c3} = {c1}*({c2}*{c3})")
print(f"({c1}+{c2})*{c3} = {(c1+c2)*c3} = {c1}*{c3} + {c2}*{c3}")